### ISSUE TITLE
Command Line control

### ISSUE THREAD

**Issue by Tilix4** [eliemichel/CodenameGogh#3]
Using Gogh through a Command Line Terminal. 

- [x] Load `.gog` file

- [ ] Run `.gog` file with inputs/arguments :
  - [x] Input File
  - [x] Output File

**Comment by eliemichel** [comment]
I think that the input/output file argument should be implemented through some kind of environment variables.

For instance, in the input node, one provides the file path `/some/path/prefix/$INPUT`, then when the graph is called in command line, one can give a value to the `$INPUT` env variable:

    gogh --graph=graph.gog -DINPUT=foobar.mp4

This will run the graph with an input value of `/some/path/prefix/foobar.mp4`

The exact syntax used to set variable values in the command line is still open. The `-D` syntax is the one used by CMake but may be a bit confusing.

Also, note that this is an **internal** notion of environment variable. This has nothing to do with system env vars like, say `$PATH` on unix or so, and should hence not interact in any way with them. We just rely on the same `$` based syntax because it will feel familiar.

**Comment by eliemichel** [comment]
What is missing now is to run the graph without starting the UI.
